filter:
    excluded_paths:
        - 'tests/*'
        - 'bin/*'
checks:
    php: true
coding_style:
    php:
        indentation:
            general:
                size: 1
        spaces:
            around_operators:
                concatenation: false
build:
    environment:
        php:
            version: 5.5.25
    tests:
        override:
            -
                command: bin/phpunit --coverage-clover=my-coverage-file
                coverage:
                    file: my-coverage-file
                    format: php-clover